### ISSUE TITLE
GO DATA section?

### ISSUE THREAD

**Issue by howraniheeresj** [CityOfDetroit/data-resources#7]
Could I get a branch of this repository where I could put some documentation for two groups:
1. Data Liaisons (internal) 
2. GO DATA Advisory Commission
Let me know the best way to do this...
Thanks,

Joel

**Comment by dexterslu** [comment]
Hey @howraniheeresj I've added two pages. Updated the Nav bar to include the Advisory Commission, the page is here https://cityofdetroit.github.io/data-resources/advisory-commission/ and the Data Liaisons page is here:
https://cityofdetroit.github.io/data-resources/resources/data-liaisons/

Let me know if you want these to be rearranged in some other way!

**Comment by dexterslu** [comment]
Closing this ticket out, feel free to re-open if you need some changes!
